from collections.abc import Callable
from typing import Any

class JSRuntimeError(Exception): ...

class JSInterpreter:
    def evaljs(self, code: str, **kwargs: object) -> Any: ...
    def export_function(self, name: str, func: Callable[..., Any]) -> None: ...
