"""
This type stub file was generated by pyright.
"""

class AttributeDict(dict):
    def __getattr__(self, key):
        ...
    


def get_pointer(ctypes_obj): # -> _Pointer[Any]:
    ...

def prettywarn(msg, warntype): # -> None:
    """Prints a suppressable warning without stack or line info."""
    ...

