"""
This type stub file was generated by pyright.
"""

from ctypes import Structure

__all__ = ["DLL", "nullfunc"]
prepath = ...
postpath = ...
if prepath != postpath:
    msg = ...
    vstr = ...
    vernum = ...
    need_update = ...
def nullfunc(*args): # -> None:
    """A simple no-op function to be used as dll replacement."""
    ...

class SDL_version(Structure):
    _fields_ = ...


class SDLFunc:
    def __init__(self, name, args=..., returns=..., added=...) -> None:
        ...
    


class DLLWarning(Warning):
    ...


class DLL:
    """Function wrapper around the different DLL functions. Do not use or
    instantiate this one directly from your user code.
    """
    def __init__(self, libinfo, libnames, path=...) -> None:
        ...
    
    def bind_function(self, funcname, args=..., returns=..., added=...): # -> Callable[..., NoReturn] | Any:
        """Binds the passed argument and return value types to the specified
        function. If the version of the loaded library is older than the
        version where the function was added, an informative exception will
        be raised if the bound function is called.
        
        Args:
            funcname (str): The name of the function to bind.
            args (List or None, optional): The data types of the C function's 
                arguments. Should be 'None' if function takes no arguments.
            returns (optional): The return type of the bound C function. Should
                be 'None' if function returns 'void'.
            added (str, optional): The version of the library in which the
                function was added, in the format '2.x.x'.
        """
        ...
    
    @property
    def libfile(self):
        """str: The filename of the loaded library."""
        ...
    
    @property
    def version_tuple(self): # -> tuple[Literal[1], Literal[0], Literal[4]] | tuple[Any, Any, Any]:
        """tuple: The version of the loaded library in the form of a
        tuple of integers (e.g. (2, 24, 1) for SDL 2.24.1).
        """
        ...
    
    @property
    def version(self): # -> Any | int:
        """int: The version of the loaded library in the form of a 4-digit
        integer (e.g. '2008' for SDL 2.0.8, '2231' for SDL 2.23.1).

        Note that this is not the same version encoding as SDL_VERSIONNUM,
        and the exact encoding used is not guaranteed.
        In new code, use version_tuple instead.
        """
        ...
    


dll = ...
def get_dll_file():
    """Gets the file name of the loaded SDL2 library."""
    ...

_bind = ...
version = ...
version_tuple = ...
