"""
This type stub file was generated by pyright.
"""

import sys
from .joystick import SDL_JoystickGUID

__all__ = ["SDL_GUID"]
SDL_GUID = SDL_JoystickGUID
_funcdefs = ...
_ctypes = ...
if sys.version_info < (3, 7, 0):
    ...
def SDL_GUIDToString(guid, pszGUID, cbGUID):
    ...

def SDL_GUIDFromString(pchGUID):
    ...

