"""
This type stub file was generated by pyright.
"""

from ctypes import Structure

__all__ = ["SDL_Locale"]
class SDL_Locale(Structure):
    _fields_ = ...
    def __repr__(self): # -> str:
        ...
    


_funcdefs = ...
_ctypes = ...
_SDL_GetPreferredLocales = ...
def SDL_GetPreferredLocales(): # -> list[Any]:
    """The base SDL2 function returns a pointer to an array of locales with an
    arbitrary length, which is just plain awful to deal with in Python. This
    wrapper returns a Python list of locales instead.
    """
    ...

