"""
This type stub file was generated by pyright.
"""

__all__ = ["CTypesView", "to_ctypes", "to_list", "to_tuple", "create_array", "MemoryView"]
_ARRAY = ...
def to_tuple(dataseq): # -> tuple[Any, ...]:
    """Converts a ``ctypes`` array to a tuple."""
    ...

def to_list(dataseq): # -> list[Any]:
    """Converts a ``ctypes`` array to a list."""
    ...

def to_ctypes(dataseq, dtype, mcount=...): # -> tuple[Any, int]:
    """Converts an arbitrary sequence to a ``ctypes`` array of a given type.

    Args:
        dataseq: A sequence to convert to a ``ctypes`` array.
        dtype (class): The ``ctypes`` data type to use for the array (e.g.
            ``ctypes.c_uint8``).
        mcount (int, optional): The number of elements in ``dataseq``. If
            not specified, this will be inferred automatically.

    Returns:
        tuple: A tuple in the form ``(valset, count)``, where ``valset`` is
        the converted ``ctypes`` array and ``count`` is the number of
        elements in the array.

    Raises:
        TypeError: if any elements in the passed sequence do not
            match the specified type.

    """
    ...

def create_array(obj, itemsize): # -> Any:
    """Creates an :obj:`array.array` copy of a given object.

    Args:
        obj: The object from which the array will be created.
        itemsize: The size (in bytes) of each item in the given object.

    Returns:
        :obj:`array.array`: The array created from the object.

    """
    ...

class CTypesView:
    """A proxy for accessing byte-wise ``ctypes`` data types.

    This class provides read-write access for arbitrary ``ctypes`` objects
    that are iterable. In case the object does not provide a :func:`buffer`
    interface for direct access, a ``CTypesView`` can copy the object's contents
    into an internal buffer from which data can be retrieved.

    Depending on the item type stored in the iterable object, you might
    need to manually specify the object's item size (in bytes). Additionally,
    you may need to manually specify the number of items in the iterable if
    it does not properly return its length using the ``len`` function.

    For certain types, such as the bytearray, the original object must not be
    reassigned after being encapsuled and used in ctypes bindings if the
    contents are not copied.

    Args:
        obj: An arbitrary iterable ``ctypes`` object to access.
        itemsize (int, optional): The size (in bytes) of each item of the
            iterable object. Defaults to ``1``.
        docopy (bool, optional): If True, the view will be created for a copy
            of the object and will not modify the original ``ctypes`` instance.
            Defalts to False (original object will be modified).
        objsize (int, optional): The number of items in the iterable object.
            If not specified, the number of items will try to be inferred
            automatically. Defaults to ``None`` (automatic inferrence).

    """
    def __init__(self, obj, itemsize=..., docopy=..., objsize=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __len__(self): # -> int:
        """Returns the length of the underlying object in bytes."""
        ...
    
    def to_bytes(self): # -> Array[c_uint8]:
        """Casts the object to an array of bytes.
        
        If the view was created with ``docopy = False`` (the default), the
        returned object provides direct read-write access to the object data.
        Otherwise, the returned object will only modify a copy of the data.

        Returns:
            :obj:`ctypes._Pointer`: A pointer to a :class:`ctypes.c_uint8`
            array.

        """
        ...
    
    def to_uint16(self): # -> Array[c_uint16]:
        """Casts the object to an array of 16-bit unsigned ints.
        
        If the view was created with ``docopy = False`` (the default), the
        returned object provides direct read-write access to the object data.
        Otherwise, the returned object will only modify a copy of the data.

        Returns:
            :obj:`ctypes._Pointer`: A pointer to a :class:`ctypes.c_uint16`
            array.

        """
        ...
    
    def to_uint32(self): # -> Array[c_uint32]:
        """Casts the object to an array of 32-bit unsigned ints.
        
        If the view was created with ``docopy = False`` (the default), the
        returned object provides direct read-write access to the object data.
        Otherwise, the returned object will only modify a copy of the data.

        Returns:
            :obj:`ctypes._Pointer`: A pointer to a :class:`ctypes.c_uint32`
            array.

        """
        ...
    
    def to_uint64(self): # -> Array[c_uint64]:
        """Casts the object to an array of 64-bit unsigned ints.
        
        If the view was created with ``docopy = False`` (the default), the
        returned object provides direct read-write access to the object data.
        Otherwise, the returned object will only modify a copy of the data.

        Returns:
            :obj:`ctypes._Pointer`: A pointer to a :class:`ctypes.c_uint64`
            array.

        """
        ...
    
    @property
    def bytesize(self): # -> int:
        """int: The size (in bytes) of the underlying object."""
        ...
    
    @property
    def view(self): # -> Any | None:
        """Provides a read/write-aware ``ctypes`` view of the encapsuled
        object.
        
        """
        ...
    
    @property
    def is_shared(self): # -> bool:
        """bool: Whether any modifications to the view will also modify the
        underlying object.

        """
        ...
    
    @property
    def object(self): # -> Any:
        """The underlying object."""
        ...
    


class MemoryView:
    """A class that provides read-write access to indexable ``ctypes`` objects.

    .. note::
       ``MemoryView`` makes heavy use of recursion for multi-dimensional
       access, making it slow for many use-cases. For better performance, the
       ``numpy`` library can be used for fast access to many array-like data
       types, but it may support fewer types of arbitrary objects than the
       ``MemoryView`` class.

    Args:
        source: An arbitrary indexable ``ctypes`` object to access.
        itemsize (int): The size (in bytes) of each item of the indexable
            object.
        strides (tuple): The length of each dimension in the object (e.g.
            ``(4, 3)`` for a 4 x 3 2D array).
        getfunc (function, optional): Deprecated, do not use.
        setfunc (function, optional): Deprecated, do not use.
        srcsize (int, optional): The size (in bytes) of the input object.
            If ``len(source)`` returns the size of the object in bytes this will
            be inferred automatically, otherwise it must be manually specified.

    """
    def __init__(self, source, itemsize, strides, getfunc=..., setfunc=..., srcsize=...) -> None:
        ...
    
    def __len__(self):
        """The length of the MemoryView over the current dimension
        (amount of items for the current dimension).
        """
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getitem__(self, index): # -> MemoryView:
        """Returns the item at the specified index."""
        ...
    
    def __setitem__(self, index, value): # -> None:
        """Sets the item at index to the specified value."""
        ...
    
    @property
    def size(self): # -> int:
        """int: The size (in bytes) of the underlying source object."""
        ...
    
    @property
    def strides(self): # -> Any:
        """tuple: The length of each dimension the MemoryView."""
        ...
    
    @property
    def itemsize(self): # -> Any:
        """int: The size (in bytes) of a single item in the object."""
        ...
    
    @property
    def ndim(self): # -> int:
        """int: The number of dimensions of the MemoryView."""
        ...
    
    @property
    def source(self): # -> Any:
        """The underlying data source."""
        ...
    


