"""
This type stub file was generated by pyright.
"""

from .compat import *

__all__ = ["Color", "is_rgb_color", "is_rgba_color", "argb_to_color", "ARGB", "rgba_to_color", "RGBA", "string_to_color", "convert_to_color", "COLOR"]
class Color:
    """A class for working with and converting RGBA colors.
    
    This class represents the 4 RGBA color channels (red, green, blue, and
    alpha transparency) as integers from 0 to 255. It also provides methods
    for converting colors to alternative color spaces (e.g. HSV or CMY).

    ``Color`` objects support basic arithmetic operations (``+, -, *, /, %``),
    which operate on a per-channel basis. For example, the operation ::

       color = color1 + color2

    is the same as ::

       color = Color()
       color.r = min(color1.r + color2.r, 255)
       color.g = min(color1.g + color2.g, 255)

    All arithmetic operations guarantee that the channel values stay within
    the allowed range of [0, 255].

    Args:
        r (int, optional): An integer between 0 and 255 indicating the red
            level of the color. Defaults to 255.
        g (int, optional): An integer between 0 and 255 indicating the green
            level of the color. Defaults to 255.
        b (int, optional): An integer between 0 and 255 indicating the blue
            level of the color. Defaults to 255.
        a (int, optional): An integer between 0 and 255 indicating the alpha
            trasparency level of the color, with 0 being fully transparent and
            255 being fully opaque. Defaults to 255.

    """
    def __init__(self, r=..., g=..., b=..., a=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __copy__(self): # -> Color:
        ...
    
    def __eq__(self, color) -> bool:
        ...
    
    def __ne__(self, color) -> bool:
        ...
    
    def __int__(self) -> int:
        ...
    
    def __long__(self): # -> int:
        ...
    
    def __float__(self): # -> float:
        ...
    
    def __index__(self): # -> int:
        ...
    
    def __oct__(self): # -> str:
        ...
    
    def __hex__(self): # -> str:
        ...
    
    def __invert__(self): # -> Color:
        ...
    
    def __mod__(self, color): # -> Color:
        ...
    
    def __div__(self, color): # -> Color:
        ...
    
    def __truediv__(self, color): # -> Color:
        ...
    
    def __mul__(self, color): # -> Color:
        ...
    
    def __sub__(self, color): # -> Color:
        ...
    
    def __add__(self, color): # -> Color:
        ...
    
    def __len__(self): # -> Literal[4]:
        ...
    
    def __getitem__(self, index):
        ...
    
    def __setitem__(self, index, val): # -> None:
        ...
    
    @property
    def r(self): # -> int:
        """"int: The 8-bit RGBA red level for the color."""
        ...
    
    @r.setter
    def r(self, val): # -> None:
        ...
    
    @property
    def g(self): # -> int:
        """"int: The 8-bit RGBA green level for the color."""
        ...
    
    @g.setter
    def g(self, val): # -> None:
        ...
    
    @property
    def b(self): # -> int:
        """"int: The 8-bit RGBA blue level for the color."""
        ...
    
    @b.setter
    def b(self, val): # -> None:
        ...
    
    @property
    def a(self): # -> int:
        """"int: The 8-bit RGBA alpha transparency level for the color."""
        ...
    
    @a.setter
    def a(self, val): # -> None:
        ...
    
    @property
    def hsva(self): # -> tuple[Literal[0], Literal[0], float | Any, float] | tuple[float | Any, float | Any, float | Any, float]:
        """tuple: A representation of the color in HSV(A) color space.
        
        The HSVA color space represents colors in terms of hue, saturation,
        value (brightness), and alpha (transparency). Hue is represented as a
        value on color wheel between 0 and 360, whereas saturation, brightness,
        and alpha are all represented as values from 0 to 100.

        Note that due to rounding errors, this may not return the exact HSVA
        values for the given color.
        
        """
        ...
    
    @hsva.setter
    def hsva(self, value): # -> None:
        ...
    
    @property
    def hsla(self): # -> tuple[Literal[0], Literal[0], float | Any, float] | tuple[float | Any, float | Any, float | Any, float]:
        """tuple: A representation of the color in HSL(A) color space.
        
        The HSLA color space represents colors in terms of hue, saturation,
        lightness, and alpha (transparency). Hue is represented as a
        value on color wheel between 0 and 360, whereas saturation, lightness,
        and alpha are all represented as values from 0 to 100.

        Note that due to rounding errors, this may not return the exact HSLA
        values for the given color.
        
        """
        ...
    
    @hsla.setter
    def hsla(self, value): # -> None:
        ...
    
    @property
    def i1i2i3(self): # -> tuple[float, float, float]:
        """tuple: A representation of the color in I1I2I3 color space.
        
        The I1I2I3 color space represents colors in terms of a color-independent
        intensity level (I1) and two chromatic channels (I2 and I3), with the
        aim of minimizing correlations between its channels for natural images.
        Intensity (I1) is represented as a float between 0.0 and 1.0, whereas
        the color channels (I2 and I3) are represented as floats between
        -0.5 and 0.5, inclusive.

        Note that due to rounding errors, this may not return the exact I1I2I3
        values for the given color.
        
        """
        ...
    
    @i1i2i3.setter
    def i1i2i3(self, value): # -> None:
        ...
    
    @property
    def cmy(self): # -> tuple[float | Any, float | Any, float | Any]:
        """tuple: A representation of the color in CMY color space.

        The CMY color space is the inverse of the RGB color space, and
        represents colors in subtractive amounts of Cyan, Magenta, and Yellow.
        All three values are represented as floats between 0.0 and 1.0.

        """
        ...
    
    @cmy.setter
    def cmy(self, value): # -> None:
        ...
    
    def normalize(self): # -> tuple[float, float, float, float]:
        """Returns the RGBA values as floats between 0 and 1.

        Returns:
            tuple: The (r, g, b, a) values of the color as normalized floats.

        """
        ...
    


def is_rgb_color(v): # -> bool:
    """Checks whether a value be converted to an RGB color.

    Args:
        v: The value to try and interpret as an RGB color.
    
    Returns:
        bool: True if the value can be interpreted as an RGB color, otherwise
        False.

    """
    ...

def is_rgba_color(v): # -> bool:
    """Checks whether a value be converted to an RGBA color.

    Args:
        v: The value to try and interpret as an RGBA color.
    
    Returns:
        bool: True if the value can be interpreted as an RGBA color, otherwise
        False.

    """
    ...

def argb_to_color(v): # -> Color:
    """Converts a 32-bit ARGB integer value to a :obj:`sdl2.ext.Color`.

    Args:
        v (int): An integer representing a color in ARGB format.

    Returns:
        :obj:`sdl2.ext.Color`: An object representing the given color.

    """
    ...

ARGB = ...
def rgba_to_color(v): # -> Color:
    """Converts a 32-bit RGBA integer value to a :obj:`sdl2.ext.Color`.

    Args:
        v (int): An integer representing a color in RGBA format.

    Returns:
        :obj:`sdl2.ext.Color`: An object representing the given color.

    """
    ...

RGBA = ...
def string_to_color(s): # -> Color:
    """Converts a hex color string to a Color value.

    Hex colors can be specified in any of the following formats:

    * #RGB
    * #RGBA
    * #RRGGBB
    * #RRGGBBAA
    * 0xRGB
    * 0xRGBA
    * 0xRRGGBB
    * 0xRRGGBBAA

    Args:
        s (str): A valid hex color in string format.

    Returns:
        :obj:`sdl2.ext.Color`: An object representing the given color.

    """
    ...

def convert_to_color(v): # -> Color:
    """Tries to convert an arbitrary object to a :obj:`sdl2.ext.Color`.

    If an integer is provided, it is assumed to be in ARGB layout.

    Args:
        v: An arbitrary object type representing a color.

    Returns:
        :obj:`sdl2.ext.Color`: An object representing the given color.

    Raises:
        ValueError: If the value could not be converted successfully.

    """
    ...

COLOR = ...
