"""
This type stub file was generated by pyright.
"""

_HASSDLTTF = ...
_HASSDLIMAGE = ...
__all__ = ["init", "quit", "get_events", "quit_requested", "TestEventProcessor"]
_sdl_subsystems = ...
def init(video=..., audio=..., timer=..., joystick=..., controller=..., haptic=..., sensor=..., events=...): # -> None:
    """Initializes SDL and its optional subsystems.

    By default, only the video and events subsystems are initialized. Note that
    the sensor subsystem requires SDL 2.0.9 or later.

    Args:
        video (bool, optional): Whether to initialize the SDL video subsystem.
            If True, the events subsystem will also be initialized. Defaults
            to True.
        audio (bool, optional): Whether to initialize the SDL audio subsystem.
            Defaults to False.
        timer (bool, optional): Whether to initialize the SDL timer subsystem.
            Defaults to False.
        joystick (bool, optional): Whether to initialize the SDL joystick
            subsystem. If True, the events subsystem will also be initialized.
            Defaults to False.
        controller (bool, optional): Whether to initialize the SDL gamecontroller
            subsystem. If True, the joystick subsystem will also be initialized.
            Defaults to False.
        haptic (bool, optional): Whether to initialize the SDL haptic (force
            feedback) subsystem. Defaults to False.
        sensor (bool, optional): Whether to initialize the SDL sensor subsystem.
            Defaults to False.
        events (bool, optional): Whether to initialize the SDL events subsystem.
            Will automatically be initialized if the video, joystick, or
            gamecontroller subsystems are enabled. Defaults to False.

    See :ref:`pygamers_pygame` for a comparison between this function and
    ``pygame.init()``.

    Raises:
        :exc:`SDLError`: If a requested SDL subsystem cannot be initialized.

    """
    ...

def quit(): # -> None:
    """Quits the SDL2 video subysystem.

    If no other subsystems are active, this will also call
    :func:`sdl2.SDL_Quit`, :func:`sdlttf.TTF_Quit` and
    :func:`sdlimage.IMG_Quit`.

    """
    ...

def get_events(): # -> list[Any]:
    """Gets all SDL events that are currently on the event queue.

    Returns:
        :obj:`List`: A list of all :obj:`~sdl2.SDL_Event` objects currently in
        the event queue.
    
    """
    ...

def quit_requested(events): # -> bool:
    """Checks for quit requests in a given event queue.

    Quit requests occur when an SDL recieves a system-level quit signal (e.g
    clicking the 'close' button on an SDL window, pressing Command-Q on macOS).
    This function makes it easier to handle these events in your code::

        running = True
        while running:
            events = sdl2.ext.get_events()
            if quit_requested(events):
                running = False

    Args:
        events (list of :obj:`sdl2.SDL_Event`): A list of SDL events to check
            for quit requests.

    Returns:
        bool: True if a quit request has occurred, otherwise False.

    """
    ...

class TestEventProcessor:
    """A simple event processor for testing purposes."""
    def run(self, window): # -> None:
        """Starts an event loop without actually processing any event.
        
        This method will run endlessly until an ``SDL_QUIT`` event occurs.

        Args:
            window (:obj:`sdl2.ext.Window`): The window within which to run
                the test event loop.
        
        """
        ...
    


