"""
This type stub file was generated by pyright.
"""

import sys

__all__ = ["ISPYTHON2", "ISPYTHON3", "utf8", "stringify", "byteify", "isiterable", "platform_is_64bit", "deprecated", "deprecation", "UnsupportedError", "ExperimentalWarning", "experimental"]
ISPYTHON2 = ...
ISPYTHON3 = ...
if sys.version_info[0] < 3:
    ...
else:
    ISPYTHON3 = ...
    long = int
    unichr = ...
    callable = ...
    unicode = str
def utf8(x): # -> str:
    """Converts input to a unicode string in a Python 2/3 agnostic manner.

    If a :obj:`bytes` object is passed, it will be decoded as UTF-8. This
    function returns :obj:`unicode` for Python 2 and :obj:`str` for Python 3.

    Args:
        x: Input to convert to a unicode string.

    Returns:
        :obj:`str` on Python 3.x, or :obj:`unicode` on Python 2.7.

    """
    ...

def stringify(x, enc=...): # -> bytes | str:
    """Converts input to a :obj:`str` in a Python 2/3 agnostic manner.

    If the input is :obj:`unicode` and the Python version is 2.7, the ``enc``
    parameter indicates the encoding to use when converting the input to
    a non-unicode string. If the input is :obj:`bytes` and the Python version
    is 3.x, the ``enc`` parameter indicates the encoding to use to decode the
    input into a unicode string.
    
    Args:
        x: Input to convert to a :obj:`str`.
        enc (str, optional): The encoding type used to encode or decode the
            input, depending on the input type and the major Python version.
            Defaults to UTF-8.

    """
    ...

def byteify(x, enc=...): # -> bytes:
    """Converts input to :obj:`bytes` in a Python 2/3 agnostic manner.

    If the input is a unicode string, the ``enc`` parameter indicates
    the encoding to use when encoding the input to :obj:`bytes`.
    
    Args:
        x: Input to convert to :obj:`bytes`.
        enc (str, optional): The encoding type used to encode any unicode
            string input. Defaults to UTF-8.

    """
    ...

def isiterable(x): # -> bool:
    """Checks whether the input is a non-string iterable.

    Args:
        x: The object to check for iterability.

    Returns:
        bool: True if the input is a valid iterable, otherwise False.

    """
    ...

def platform_is_64bit(): # -> bool:
    """Checks whether the Python interpreter is 64-bit.
    
    Returns:
        bool: True if running on 64-bit Python, otherwise False.

    """
    ...

def deprecated(func): # -> Callable[..., Any]:
    ...

def deprecation(message): # -> None:
    ...

class UnsupportedError(RuntimeError):
    ...


class ExperimentalWarning(Warning):
    def __init__(self, obj, msg=...) -> None:
        """Creates a ExperimentalWarning for the specified obj.

        If a message is passed in msg, it will be printed instead of the
        default message.
        """
        ...
    
    def __str__(self) -> str:
        ...
    


def experimental(func): # -> Callable[..., Any]:
    ...

