"""
This type stub file was generated by pyright.
"""

from .compat import *

"""
A component-based entity system framework.

ebs loosely follows a component oriented pattern to separate object
instances, carried data and processing logic within applications or
games. It uses a entity based approach, in which object instances are
unique identifiers, while their data is managed within components, which
are separately stored. For each individual component type a processing
system will take care of all necessary updates for the World
environment.
"""
__all__ = ["Entity", "World", "System", "Applicator"]
class Entity:
    """A simple object entity.

    An entity is a specific object living in the application world. It
    does not carry any data or application logic, but merely acts as
    identifier label for data that is maintained in the application
    world itself.

    As such, it is an composition of components, which would not exist
    without the entity identifier. The entity itself is non-existent to
    the application world as long as it does not carry any data that can
    be processed by a system within the application world.
    """
    def __new__(cls, world, *args, **kwargs): # -> Self:
        ...
    
    def __repr__(self): # -> Any:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __getattr__(self, name): # -> Any:
        """Gets the component data related to the Entity."""
        ...
    
    def __setattr__(self, name, value): # -> None:
        """Sets the component data related to the Entity."""
        ...
    
    def __delattr__(self, name): # -> None:
        """Deletes the component data related to the Entity."""
        ...
    
    def delete(self): # -> None:
        """Removes the Entity from the world it belongs to."""
        ...
    
    @property
    def id(self): # -> Any:
        """The id of the Entity."""
        ...
    
    @property
    def world(self): # -> Any:
        """The world the Entity resides in."""
        ...
    


class World:
    """A simple application world.

    An application world defines the combination of application data and
    processing logic and how the data will be processed. As such, it is
    a container object in which the application is defined.

    The application world maintains a set of entities and their related
    components as well as a set of systems that process the data of the
    entities. Each processing system within the application world only
    operates on a certain set of components, but not all components of
    an entity at once.

    The order in which data is processed depends on the order of the
    added systems.
    """
    def __init__(self) -> None:
        """Creates a new World instance."""
        ...
    
    def combined_components(self, comptypes): # -> Generator[tuple[Any, ...], Any, None]:
        """A generator view on combined sets of component items."""
        ...
    
    def add_componenttype(self, classtype): # -> None:
        """Adds a supported component type to the World."""
        ...
    
    def delete(self, entity): # -> None:
        """Removes an Entity from the World, including all its data."""
        ...
    
    def delete_entities(self, entities): # -> None:
        """Removes multiple entities from the World at once."""
        ...
    
    def get_components(self, componenttype): # -> list[Any]:
        """Gets all existing components for a sepcific component type.

        If no components could be found for the passed component types, an
        empty list is returned.
        """
        ...
    
    def get_entities(self, component): # -> list[Any]:
        """Gets the entities using the passed component.

        Note: this will not perform an identity check on the component
        but rely on its __eq__ implementation instead.
        """
        ...
    
    def add_system(self, system): # -> None:
        """Adds a processing system to the world.

        The system will be added as last item in the processing order. Every
        object can be added as long as it contains

           * a 'componenttypes' attribute that is iterable and contains the
            class types to be processed
           * a 'process()' method, receiving two arguments, the world and
             components

        If the object contains a 'is_applicator' attribute that evaluates to
        True, the system will operate on combined sets of components.
        """
        ...
    
    def insert_system(self, index, system): # -> None:
        """Adds a processing system to the world.

        The system will be added at the specific position of the
        processing order.
        """
        ...
    
    def remove_system(self, system): # -> None:
        """Removes a processing system from the world."""
        ...
    
    def process(self): # -> None:
        """Processes all components within their corresponding systems."""
        ...
    
    @property
    def systems(self): # -> tuple[Any, ...]:
        """Gets the systems bound to the world."""
        ...
    
    @property
    def componenttypes(self): # -> dict_values[Any, Any]:
        """Gets the supported component types of the world."""
        ...
    


class System:
    """A processing system for component data.

    A processing system within an application world consumes the
    components of all entities, for which it was set up. At time of
    processing, the system does not know about any other component type
    that might be bound to any entity.

    Also, the processing system does not know about any specific entity,
    but only is aware of the data carried by all entities.
    """
    def __init__(self) -> None:
        ...
    
    def process(self, world, components):
        """Processes component items.

        This must be implemented by inheriting classes.
        """
        ...
    


class Applicator(System):
    """A processing system for combined data sets."""
    def __init__(self) -> None:
        ...
    


