"""
This type stub file was generated by pyright.
"""

from .compat import *

"""General purpose event handling routines"""
__all__ = ["EventHandler", "MPEventHandler"]
_HASMP = ...
class EventHandler:
    """A simple event handling class, which manages callbacks to be
    executed.
    """
    def __init__(self, sender) -> None:
        ...
    
    def __call__(self, *args): # -> list[Any]:
        """Executes all callbacks.

        Executes all connected callbacks in the order of addition,
        passing the sender of the EventHandler as first argument and the
        optional args as second, third, ... argument to them.
        """
        ...
    
    def __iadd__(self, callback): # -> Self:
        """Adds a callback to the EventHandler."""
        ...
    
    def __isub__(self, callback): # -> Self:
        """Removes a callback from the EventHandler."""
        ...
    
    def __len__(self): # -> int:
        """Gets the amount of callbacks connected to the EventHandler."""
        ...
    
    def __getitem__(self, index):
        ...
    
    def __setitem__(self, index, value): # -> None:
        ...
    
    def __delitem__(self, index): # -> None:
        ...
    
    def add(self, callback): # -> None:
        """Adds a callback to the EventHandler."""
        ...
    
    def remove(self, callback): # -> None:
        """Removes a callback from the EventHandler."""
        ...
    


class MPEventHandler(EventHandler):
    """An asynchronous event handling class in which callbacks are
    executed in parallel.

    It is the responsibility of the caller code to ensure that every
    object used maintains a consistent state. The MPEventHandler class
    will not apply any locks, synchronous state changes or anything else
    to the arguments being used. Consider it a "fire-and-forget" event
    handling strategy
    """
    def __init__(self, sender, maxprocs=...) -> None:
        ...
    
    def __call__(self, *args): # -> MapResult[Any]:
        ...
    


