"""
This type stub file was generated by pyright.
"""

__all__ = ["show_cursor", "hide_cursor", "cursor_hidden", "mouse_coords", "mouse_delta", "warp_mouse", "mouse_button_state", "ButtonState"]
class ButtonState:
    """A class representing the state of the mouse buttons.

    Args:
        buttonmask (int): The raw SDL button mask to parse.

    Attributes:
        raw (int): The raw SDL button mask representing the button state.

    """
    def __init__(self, buttonmask) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, s2) -> bool:
        ...
    
    def __ne__(self, s2) -> bool:
        ...
    
    @property
    def any_pressed(self):
        """bool: True if any buttons are currently pressed, otherwise False.
        """
        ...
    
    @property
    def left(self): # -> int:
        """int: The state of the left mouse button (0 = up, 1 = down).
        """
        ...
    
    @property
    def right(self): # -> int:
        """int: The state of the right mouse button (0 = up, 1 = down).
        """
        ...
    
    @property
    def middle(self): # -> int:
        """int: The state of the middle mouse button (0 = up, 1 = down).
        """
        ...
    
    @property
    def x1(self): # -> int:
        """int: The state of the first extra mouse button (0 = up, 1 = down).
        """
        ...
    
    @property
    def x2(self): # -> int:
        """int: The state of the second extra mouse button (0 = up, 1 = down).
        """
        ...
    


def show_cursor(): # -> None:
    """Unhides the mouse cursor if it is currently hidden.

    """
    ...

def hide_cursor(): # -> None:
    """Hides the mouse cursor if it is currently visible.

    """
    ...

def cursor_hidden():
    """Checks whether the mouse cursor is currently visible.

    Returns:
        bool: True if the cursor is hidden, otherwise False.

    """
    ...

def mouse_coords(desktop=...): # -> tuple[int, int]:
    """Get the current x/y coordinates of the mouse cursor.

    By default, this function reports the coordinates relative to the top-left
    corner of the SDL window that currently has focus. To obtain the mouse
    coordinates relative to the top-right corner of the full desktop, this
    function can optionally be called with ``desktop`` argument set to True.

    Args:
        desktop (bool, optional): If True, reports the mouse coordinates
            relative to the full desktop instead of the currently-focused SDL
            window. Defaults to False.

    Returns:
        tuple: The current (x, y) coordinates of the mouse cursor.

    """
    ...

def mouse_button_state(): # -> ButtonState:
    """Gets the current state of each button of the mouse.

    Mice in SDL are currently able to have up to 5 buttons: left, right, middle,
    and two extras (x1 and x2). You can check each of these individually, or
    alternatively check whether any buttons have been pressed::

       bstate = mouse_button_state()
       if bstate.any_pressed:
           if bstate.left == 1:
               print("left button down!")
           if bstate.right == 1:
               print("right button down!")

    Returns:
        :obj:`ButtonState`: A representation of the current button state of the
        mouse.

    """
    ...

def mouse_delta(): # -> tuple[int, int]:
    """Get the relative change in cursor position since last checked.

    The first time this function is called, it will report the (x, y) change in
    cursor position since the SDL video or event system was initialized.
    Subsequent calls to this function report the change in position since the
    previous time the function was called.

    Returns:
        tuple: The (x, y) change in cursor coordinates since the function was
        last called.

    """
    ...

def warp_mouse(x, y, window=..., desktop=...): # -> None:
    """Warps the mouse cursor to a given location on the screen.

    By default, this warps the mouse cursor relative to the top-left corner of
    whatever SDL window currently has mouse focus. For example,::

       warp_mouse(400, 300)

    would warp the mouse to the middle of a 800x600 SDL window. Alternatively,
    the cursor can be warped within a specific SDL window or relative to the
    full desktop.

    .. NOTE: For security reasons, the Wayland protocol does not allow programs
             to change the cursor position. However, it is possible to warp the
             cursor when using XWayland (the default for SDL2).

    Args:
        x (int): The new X position for the mouse cursor.
        y (int): The new Y position for the mouse cursor.
        window (:obj:`SDL_Window` or :obj:`~sdl2.ext.Window`, optional): The
            SDL window within which to warp the mouse cursor. If not specified
            (the default), the cursor will be warped within the SDL window that
            currently has mouse focus.
        desktop (bool, optional): If True, the mouse cursor will be warped
            relative to the full desktop instead of the current SDL window.
            Defaults to False.
    
    """
    ...

