"""
This type stub file was generated by pyright.
"""

import numpy
from .array import MemoryView

_HASNUMPY = ...
__all__ = ["PixelView", "SurfaceArray", "pixels2d", "pixels3d", "surface_to_ndarray"]
class PixelView(MemoryView):
    """A 2D memory view for reading and writing SDL surface pixels.

    This class uses a ``view[y][x]`` layout, with the y-axis as the first
    dimension and the x-axis as the second. ``PixelView`` objects currently do
    not support array slicing, but support negative indexing as of
    PySDL2 0.9.10.

    If the source surface is RLE-accelerated, it will be locked automatically
    when the view is created and you will need to re-lock the surface using
    :func:`SDL_UnlockSurface` once you are done with the view.

    .. warning::
       The source surface should not be freed or deleted until the view is no
       longer needed. Accessing the view for a freed surface will likely cause
       Python to hard-crash.

    .. note:: 
       This class is implemented on top of the :class:`~sdl2.ext.MemoryView`
       class. As such, it makes heavy use of recursion to access rows and
       will generally be much slower than the :mod:`numpy`-based
       :func:`~sdl2.ext.pixels2d` and :func:`~sdl2.ext.pixels3d` functions.

    Args:
        source (:obj:`~sdl2.SDL_Surface`, :obj:`~sdl2.ext.SoftwareSprite`): The
            SDL surface to access with the view.

    """
    def __init__(self, source) -> None:
        ...
    


def pixels2d(source, transpose=...): # -> SurfaceArray:
    """Creates a 2D Numpy array view for a given SDL surface.

    This function casts the surface pixels to a 2D Numpy array view, providing
    read and write access to the underlying surface. If the source surface is
    RLE-accelerated, it will be locked automatically when the view is created
    and you will need to re-lock the surface using :func:`SDL_UnlockSurface`
    once you are done with the array.

    By default, the array is returned in ``arr[x][y]`` format with the x-axis
    as the first dimension, contrary to PIL and PyOpenGL convention. To obtain 
    an ``arr[y][x]`` array, set the ``transpose`` argument to ``False``.

    .. warning::
       The source surface should not be freed or deleted until the array is no
       longer needed. Accessing the array for a freed surface will likely cause
       Python to hard-crash.

    .. note::
       This function requires Numpy to be installed in the current Python
       environment.

    Args:
        source (:obj:`~sdl2.SDL_Surface`, :obj:`~sdl2.ext.SoftwareSprite`): The
            SDL surface to cast to a numpy array.
        transpose (bool, optional): Whether the output array should be
            transposed to have ``arr[x][y]`` axes instead of ``arr[y][x]`` axes.
            Defaults to ``True``.

    Returns:
        :obj:`numpy.ndarray`: A 2-dimensional Numpy array containing the integer
        color values for each pixel in the surface.

    Raises:
        RuntimeError: If Numpy could not be imported.
   
    """
    ...

def pixels3d(source, transpose=...): # -> SurfaceArray:
    """Creates a 3D Numpy array view for a given SDL surface.

    This function casts the surface pixels to a 3D Numpy array view, providing
    read and write access to the underlying surface. If the source surface is
    RLE-accelerated, it will be locked automatically when the view is created
    and you will need to re-lock the surface using :func:`SDL_UnlockSurface`
    once you are done with the array.

    By default, the array is returned in ``arr[x][y]`` format with the x-axis
    as the first dimension, contrary to PIL and PyOpenGL convention. To obtain 
    an ``arr[y][x]`` array, set the ``transpose`` argument to ``False``.

    When creating a 3D array view, the order of the RGBA values for each pixel
    may be reversed for some common surface pixel formats (e.g. 'BGRA' for a
    ``SDL_PIXELFORMAT_ARGB8888`` surface). To correct this, you can call
    ``numpy.flip(arr, axis=2)`` to return a view of the array with the expected
    channel order.

    .. warning::
       The source surface should not be freed or deleted until the array is no
       longer needed. Accessing the array for a freed surface will likely cause
       Python to hard-crash.

    .. note::
       This function requires Numpy to be installed in the current Python
       environment.

    Args:
        source (:obj:`~sdl2.SDL_Surface`, :obj:`~sdl2.ext.SoftwareSprite`): The
            SDL surface to cast to a numpy array.
        transpose (bool, optional): Whether the output array should be
            transposed to have ``arr[x][y]`` axes instead of ``arr[y][x]`` axes.
            Defaults to ``True``.

    Returns:
        :obj:`numpy.ndarray`: A 3-dimensional Numpy array containing the values
        of each byte for each pixel in the surface.

    Raises:
        RuntimeError: If Numpy could not be imported.
   
    """
    ...

def surface_to_ndarray(source, ndim=...): # -> NDArray[Any]:
    """Returns a copy of an SDL surface as a Numpy array.
    
    The main difference between this function and :func:`~sdl2.ext.pixels2d` or
    :func:`~sdl2.ext.pixels3d` is that it returns a copy of the surface instead
    of a view, meaning that modifying the returned array will not affect the
    original surface (or vice-versa). This function is also slightly safer,
    as it does not assume that the source surface has been kept in memory.

    When creating a 3D array copy, the order of the RGBA values for each pixel
    may be reversed for some common surface pixel formats (e.g. 'BGRA' for a
    ``SDL_PIXELFORMAT_ARGB8888`` surface). To correct this, you can call
    ``numpy.flip(arr, axis=2)`` to return a view of the array with the expected
    channel order.

    .. note::
       Unlike :func:`~sdl2.ext.pixels2d` or :func:`~sdl2.ext.pixels3d`, this
       function always returns arrays with the y-axis as the first dimension
       (e.g. ``arr[y][x]``).

    .. note::
       This function requires Numpy to be installed in the current Python
       environment.

    Args:
        source (:obj:`~sdl2.SDL_Surface`, :obj:`~sdl2.ext.SoftwareSprite`): The
            SDL surface to convert to a numpy array.
        ndim (int, optional): The number of dimensions for the returned array,
            must be either 2 (for a 2D array) or 3 (for a 3D array). Defaults
            to 3.

    Returns:
        :obj:`numpy.ndarray`: A Numpy array containing a copy of the pixel data
        for the given surface.

    Raises:
        RuntimeError: If Numpy could not be imported.

    """
    ...

class SurfaceArray(numpy.ndarray if _HASNUMPY else object):
    """A Numpy array that keeps a reference to its parent SDL surface.

    This class is used to keep track of the original source object for
    :func:`~sdl2.ext.pixels2d` or :func:`~sdl2.ext.pixels3d` to prevent it from
    being automatically freed during garbage collection. It should never be used
    for any other purpose.
    
    """
    def __new__(cls, shape, dtype=..., buffer_=..., offset=..., strides=..., order=..., source=..., surface=...): # -> Self | None:
        ...
    
    def __array_finalize__(self, sfarray): # -> None:
        ...
    


