"""
This type stub file was generated by pyright.
"""

import sys

__all__ = ["open_zipfile", "open_tarfile", "open_url", "Resources"]
if sys.version_info[0] >= 3:
    ...
else:
    ...
def open_zipfile(archive, filename, directory=...): # -> BytesIO:
    """Retrieves a given file from a ZIP archive.

    Args:
        archive (:obj:`~zipfile.ZipFile`, str): The ZipFile object or path to
            the ZIP archive containing the desired file.
        filename (str): The name of the file to retrieve from the archive.
        directory (str, optional): The path to the directory within the archive
            containing the file to retrieve. Defaults to the root level of the
            archive.

    Returns:
        :obj:`~io.BytesIO`: A Python bytestream object containing the requested
        file.

    Raises:
        KeyError: If the given file could not be found within the archive.
        TypeError: If the archive is not a valid ZIP archive.

    """
    ...

def open_tarfile(archive, filename, directory=..., ftype=...): # -> BytesIO:
    """Retrieves a given file from a TAR archive.

    If the TAR archive uses ``.tar.gz`` or ``.tar.bz2`` compression and the
    file name does not contain either of these identifiers, the compression
    type must be manually specified.

    Args:
        archive (:obj:`~tarfile.TarFile`, str): The TarFile object or path to
            the TAR archive containing the desired file.
        filename (str): The name of the file to retrieve from the archive.
        directory (str, optional): The path to the directory within the archive
            containing the file to retrieve. Defaults to the root level of the
            archive.
        ftype (str, optional): The compression type (if any) used for the TAR
            file, can be either 'gz', 'bz2', or None (no compression). If not
            specified, will default to assuming no compression.

    Returns:
        :obj:`~io.BytesIO`: A Python bytestream object containing the requested
        file.

    Raises:
        KeyError: If the given file could not be found within the archive.
        TypeError: If the archive is not a supported TAR archive.

    """
    ...

def open_url(filename, basepath=...): # -> _UrlopenRet:
    ...

class Resources:
    """A container class for managing application resource files.
    
    This class eases access to resources by allowing access using relative
    paths, scanning archives to locate files, and more.

    Args:
        path (str, optional): The path of a resource directory with which to
            initialze the container. Defaults to ``None``.
        subdir (str, optional): Deprecated, do not use.
        excludepattern (str, optional): A regular expression indicating
            which directories (if any) to ignore if initializing the
            container with a resource path. Defaults to ``None``.

    """
    def __init__(self, path=..., subdir=..., excludepattern=...) -> None:
        ...
    
    def add(self, filename): # -> None:
        """Adds a file to the Resources container.

        If the given file is a supported archive, its contents will be scanned
        and added to the container.

        Args:
            filename (str): The filepath of the resource to add to the
                container.

        Raises:
            ValueError: If the file does not exist at the provided path.

        """
        ...
    
    def add_file(self, filename): # -> None:
        """Adds a file without scanning to the Resources container.

        Unlike :meth:`add`, this method will not attempt to add the contents
        of any provided archives to the container.

        Args:
            filename (str): The filepath of the resource to add to the
                container.

        Raises:
            ValueError: If the file does not exist at the provided path.

        """
        ...
    
    def add_archive(self, filename, typehint=...): # -> None:
        """Adds a ``.zip`` or ``.tar`` archive to the container.

        This will scan the passed archive and add its contents to the
        list of available resources. Currently ``.zip``, ``.tar``,
        ``.tar.bz2``, and ``.tar.gz`` formats are supported.

        Args:
            filename (str): The filepath of the archive to scan and add to the
                container.
            typehint (str, optional): The format of the archive to add to the
                container, required if using a custom file extension. Must be
                one of ``zip``, ``tar``, ``tarbz2``, or ``targz``. Defaults to
                ``zip`` if not specified.

        Raises:
            ValueError: If the file does not exist at the provided path, or if
                the file is not a supported archive type.

        """
        ...
    
    def get(self, filename): # -> BytesIO:
        """Retrieves a resource file by name from the container.

        Args:
            filename (str): The file name of the resource to retrieve.

        Returns:
            :obj:`~io.BytesIO`: A Python bytestream object containing the
            retrieved resource file.

        Raises:
            KeyError: If the given file could not be found.

        """
        ...
    
    def get_filelike(self, filename): # -> BytesIO | BufferedReader[_BufferedReaderStream]:
        ...
    
    def get_path(self, filename): # -> LiteralString:
        """Gets the path of a given resource file.

        If the file is only available within an archive, a string in the form
        ``filename@archivename`` will be returned.

        Args:
            filename (str): The file name of the resource to locate.

        Returns:
            str: The absolute path of the resource file, or the archive
            identifier string if the resource is inside an archive.

        Raises:
            KeyError: If the given file could not be found.

        """
        ...
    
    def scan(self, path, subdir=..., excludepattern=...): # -> None:
        """Scans a path, adding all matching files to the container.

        If a located file is a ``.zip`` or ``.tar`` archive, its
        contents will be indexed and added to the container automatically.

        Args:
            path (str): The path of the directory to scan.
            subdir (str, optional): Deprecated, do not use.
            excludepattern (str, optional): A regular expression indicating
                which directories (if any) within the file structure of the
                given path to exclude from indexing. Defaults to ``None``. 

        Raises:
            ValueError: If the specified path does not exist.

        """
        ...
    


