"""
This type stub file was generated by pyright.
"""

from .ebs import System

__all__ = ["SpriteFactory", "SoftwareSpriteRenderSystem", "SpriteRenderSystem", "TextureSpriteRenderSystem", "TEXTURE", "SOFTWARE"]
TEXTURE = ...
SOFTWARE = ...
class SpriteFactory:
    """A factory class for creating Sprite components."""
    def __init__(self, sprite_type=..., **kwargs) -> None:
        """Creates a new SpriteFactory.

        The SpriteFactory can create TextureSprite or SoftwareSprite
        instances, depending on the sprite_type being passed to it,
        which can be SOFTWARE or TEXTURE. The additional kwargs are used
        as default arguments for creating sprites within the factory
        methods.
        """
        ...
    
    @property
    def sprite_type(self): # -> int:
        """The sprite type created by the factory."""
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def create_sprite_render_system(self, *args, **kwargs): # -> TextureSpriteRenderSystem | SoftwareSpriteRenderSystem:
        """Creates a new SpriteRenderSystem.

        For TEXTURE mode, the passed args and kwargs are ignored and the
        Renderer or SDL_Renderer passed to the SpriteFactory is used.
        """
        ...
    
    def from_image(self, img): # -> TextureSprite | SoftwareSprite:
        """Creates a Sprite from the passed PIL.Image or image file name."""
        ...
    
    def from_surface(self, tsurface, free=...): # -> TextureSprite | SoftwareSprite:
        """Creates a Sprite from the passed SDL_Surface.

        If free is set to True, the passed surface will be freed
        automatically.
        """
        ...
    
    def from_object(self, obj): # -> TextureSprite | SoftwareSprite:
        """Creates a Sprite from an arbitrary object."""
        ...
    
    def from_color(self, color, size, bpp=..., masks=...): # -> TextureSprite | SoftwareSprite:
        """Creates a sprite with a certain color.
        """
        ...
    
    def from_text(self, text, **kwargs): # -> TextureSprite | SoftwareSprite:
        """Creates a Sprite from a string of text."""
        ...
    
    def create_sprite(self, **kwargs): # -> TextureSprite | SoftwareSprite:
        """Creates an empty Sprite.

        This will invoke create_software_sprite() or
        create_texture_sprite() with the passed arguments and the set
        default arguments.
        """
        ...
    
    def create_software_sprite(self, size, bpp=..., masks=...): # -> SoftwareSprite:
        """Creates a software sprite.

        A size tuple containing the width and height of the sprite and a
        bpp value, indicating the bits per pixel to be used, need to be
        provided.
        """
        ...
    
    def create_texture_sprite(self, renderer, size, pformat=..., access=...): # -> TextureSprite:
        """Creates a texture sprite.

        A size tuple containing the width and height of the sprite needs
        to be provided.

        TextureSprite objects are assumed to be static by default,
        making it impossible to access their pixel buffer in favour for
        faster copy operations. If you need to update the pixel data
        frequently or want to use the texture as target for rendering
        operations, access can be set to the relevant
        SDL_TEXTUREACCESS_* flag.
        """
        ...
    


class SpriteRenderSystem(System):
    """A rendering system for Sprite components.

    This is a base class for rendering systems capable of drawing and
    displaying Sprite-based objects. Inheriting classes need to
    implement the rendering capability by overriding the render()
    method.
    """
    def __init__(self) -> None:
        ...
    
    def render(self, sprites, x=..., y=...): # -> None:
        """Renders the passed sprites.

        This is a no-op function and needs to be implemented by inheriting
        classes.
        """
        ...
    
    def process(self, world, components): # -> None:
        """Draws the passed SoftSprite objects on the Window's surface."""
        ...
    
    @property
    def sortfunc(self): # -> Callable[..., Any] | Callable[..., object]:
        """Sort function for the component processing order.

        The default sort order is based on the depth attribute of every
        sprite. Lower depth values will cause sprites to be drawn below
        sprites with higher depth values.
        """
        ...
    
    @sortfunc.setter
    def sortfunc(self, value): # -> None:
        """Sort function for the component processing order.

        The default sort order is based on the depth attribute of every
        sprite. Lower depth values will cause sprites to be drawn below
        sprites with higher depth values.
        """
        ...
    


class SoftwareSpriteRenderSystem(SpriteRenderSystem):
    """A rendering system for SoftwareSprite components.

    The SoftwareSpriteRenderSystem class uses a Window as drawing device to
    display Sprite surfaces. It uses the Window's internal SDL surface as
    drawing context, so that GL operations, such as texture handling or
    using SDL renderers is not possible.
    """
    def __init__(self, window) -> None:
        """Creates a new SoftwareSpriteRenderSystem for a specific Window."""
        ...
    
    def render(self, sprites, x=..., y=...): # -> None:
        """Draws the passed sprites (or sprite) on the Window's surface.

        x and y are optional arguments that can be used as relative drawing
        location for sprites. If set to None, the location information of the
        sprites are used. If set and sprites is an iterable, such as a list of
        SoftwareSprite objects, x and y are relative location values that will
        be added to each individual sprite's position. If sprites is a single
        SoftwareSprite, x and y denote the absolute position of the
        SoftwareSprite, if set.
        """
        ...
    


class TextureSpriteRenderSystem(SpriteRenderSystem):
    """A rendering system for TextureSprite components.

    The TextureSpriteRenderSystem class uses a SDL_Renderer as drawing
    device to display TextureSprite objects.
    """
    def __init__(self, target) -> None:
        """Creates a new TextureSpriteRenderSystem.

        target can be a Window, SDL_Window, Renderer or SDL_Renderer.
        If it is a Window or SDL_Window instance, a Renderer will be
        created to acquire the SDL_Renderer.
        """
        ...
    
    def __del__(self): # -> None:
        ...
    
    def render(self, sprites, x=..., y=...): # -> None:
        """Draws the passed sprites (or sprite).

        x and y are optional arguments that can be used as relative
        drawing location for sprites. If set to None, the location
        information of the sprites are used. If set and sprites is an
        iterable, such as a list of TextureSprite objects, x and y are
        relative location values that will be added to each individual
        sprite's position. If sprites is a single TextureSprite, x and y
        denote the absolute position of the TextureSprite, if set.
        """
        ...
    


