"""
This type stub file was generated by pyright.
"""

import abc

__all__ = ["Sprite", "SoftwareSprite", "TextureSprite"]
class Sprite:
    """A simple 2D object."""
    __metaclass__ = abc.ABCMeta
    def __init__(self) -> None:
        """Creates a new Sprite."""
        ...
    
    @property
    def position(self): # -> tuple[int | Any, int | Any]:
        """The top-left position of the Sprite as tuple."""
        ...
    
    @position.setter
    def position(self, value): # -> None:
        """The top-left position of the Sprite as tuple."""
        ...
    
    @property
    @abc.abstractmethod
    def size(self): # -> None:
        """The size of the Sprite as tuple."""
        ...
    
    @property
    def area(self): # -> tuple[int | Any, int | Any, Any, Any]:
        """The rectangular area occupied by the Sprite."""
        ...
    


class SoftwareSprite(Sprite):
    """A simple, visible, pixel-based 2D object using software buffers."""
    def __init__(self, imgsurface, free) -> None:
        """Creates a new SoftwareSprite."""
        ...
    
    def __del__(self): # -> None:
        """Releases the bound SDL_Surface, if it was created by the
        SoftwareSprite.
        """
        ...
    
    @property
    def size(self): # -> tuple[Any, Any]:
        """The size of the SoftwareSprite as tuple."""
        ...
    
    def subsprite(self, area): # -> SoftwareSprite:
        """Creates another SoftwareSprite from a part of the SoftwareSprite.

        The two sprites share pixel data, so if the parent sprite's surface is
        not managed by the sprite (free is False), you will need to keep it
        alive while the subsprite exists."""
        ...
    
    def __repr__(self): # -> str:
        ...
    


class TextureSprite(Sprite):
    """A simple, visible, texture-based 2D object, using a renderer."""
    def __init__(self, texture, free=...) -> None:
        """Creates a new TextureSprite."""
        ...
    
    def __del__(self): # -> None:
        """Releases the bound SDL_Texture."""
        ...
    
    @property
    def center(self): # -> SDL_Point | None:
        """The center of the TextureSprite as tuple."""
        ...
    
    @center.setter
    def center(self, value): # -> None:
        """Sets the center of the TextureSprite."""
        ...
    
    @property
    def size(self): # -> tuple[int, int]:
        """The size of the TextureSprite as tuple."""
        ...
    
    def __repr__(self): # -> str:
        ...
    


