"""
This type stub file was generated by pyright.
"""

from .ebs import System

"""User interface elements."""
__all__ = ["RELEASED", "HOVERED", "PRESSED", "BUTTON", "CHECKBUTTON", "TEXTENTRY", "UIProcessor", "UIFactory"]
RELEASED = ...
HOVERED = ...
PRESSED = ...
BUTTON = ...
CHECKABLE = ...
CHECKBUTTON = ...
TEXTENTRY = ...
class UIFactory:
    """A simple UI factory for creating GUI elements for software- or
    texture-based rendering."""
    def __init__(self, spritefactory, **kwargs) -> None:
        """Creates a new UIFactory.

        The additional kwargs will be stored internally and passed to the
        UI creation methods as arguments. Hence they can act as default
        arguments to be passed to each and every UI element to be
        created.
        """
        ...
    
    def from_image(self, uitype, fname):
        """Creates a new UI element from the passed image file."""
        ...
    
    def from_surface(self, uitype, surface, free=...):
        """Creates a new UI element from the passed SDL surface."""
        ...
    
    def from_object(self, uitype, obj):
        """Creates a new UI element from an arbitrary object."""
        ...
    
    def from_color(self, uitype, color, size):
        """Creates a new UI element using a certain color."""
        ...
    
    def create_button(self, **kwargs):
        """Creates a new Sprite that can react on mouse events."""
        ...
    
    def create_checkbutton(self, **kwargs):
        """Creates a new Sprite that can react on mouse events and
        retains its state."""
        ...
    
    def create_text_entry(self, **kwargs):
        """Creates a new Sprite that can react on text input."""
        ...
    
    def __repr__(self): # -> str:
        ...
    


class UIProcessor(System):
    """A processing system for user interface elements and events."""
    def __init__(self) -> None:
        """Creates a new UIProcessor."""
        ...
    
    def activate(self, component): # -> None:
        """Activates a control to receive input."""
        ...
    
    def deactivate(self, component): # -> None:
        """Deactivates the currently active control."""
        ...
    
    def passevent(self, component, event): # -> None:
        """Passes the event to a component without any additional checks
        or restrictions.
        """
        ...
    
    def textinput(self, component, event): # -> None:
        """Checks, if an active component is available and matches the
        passed component and passes the event on to that component."""
        ...
    
    def mousemotion(self, component, event): # -> None:
        """Checks, if the event's motion position is on the component
        and executes the component's event handlers on demand.

        If the motion event position is not within the area of the
        component, nothing will be done. In case the component is a
        Button, its state will be adjusted to reflect, if it is
        currently hovered or not.
        """
        ...
    
    def mousedown(self, component, event): # -> None:
        """Checks, if the event's button press position is on the
        component and executes the component's event handlers on demand.

        If the button press position is not within the area of the
        component, nothing will be done. In case the component is a
        Button, its state will be adjusted to reflect, if it is
        currently pressed or not. In case the component is a TextEntry and
        the pressed button is the primary mouse button, the component will
        be marked as the next control to activate for text input.
        """
        ...
    
    def mouseup(self, component, event): # -> None:
        """Checks, if the event's button release position is on the
        component and executes the component's event handlers on demand.

        If the button release position is not within the area of the
        component, nothing will be done. In case the component is a
        Button, its state will be adjusted to reflect, whether it is
        hovered or not. If the button release followed a button press on
        the same component and if the button is the primary button, the
        click() event handler is invoked, if the component is a Button.
        """
        ...
    
    def dispatch(self, obj, event): # -> None:
        """Passes an event to the given object.

        If obj is a World object, UI relevant components will receive
        the event, if they support the event type.

        If obj is a single object, obj.events MUST be a dictionary
        consisting of SDL event type identifiers and EventHandler
        instances bound to the object. obj also must have a 'uitype' attribute
        referring to the UI type of the object.
        If obj is an iterable, such as a list or set, every item within
        obj MUST feature an 'events' and 'uitype' attribute as described
        above.
        """
        ...
    
    def process(self, world, components): # -> None:
        """The UIProcessor class does not implement the process() method
        by default. Instead it uses dispatch() to send events around to
        components.
        """
        ...
    
    def __repr__(self): # -> Literal['UIProcessor()']:
        ...
    


